name: Docker Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [[self-hosted, linux, ARM64], ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate build info
        run: scripts/generate-git-info.sh > scripts/packages/git-info
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: 'pyroscope/pyroscope-dev:${{ runner.arch }}-git-${{ github.sha }}'

  combine:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: pull X64 image
        run: docker pull 'pyroscope/pyroscope:X64-git-${{ github.sha }}'
      - name: pull ARM64 image
        run: docker pull 'pyroscope/pyroscope:ARM64-git-${{ github.sha }}'
      - name: create manifest
        run: docker manifest create 'pyroscope/pyroscope-dev:git-${{ github.sha }}' $(docker image inspect pyroscope/pyroscope:X64-git-${{ github.sha }} | jq .[].Id | tr -d '"') $(docker image inspect pyroscope/pyroscope:ARM64-git-${{ github.sha }} | jq .[].Id | tr -d '"')
      - name: push manifest
        run: docker manifest push 'pyroscope/pyroscope-dev:git-${{ github.sha }}'
