name: Docker Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# this job builds docker image on 2 separate runners (for different arches)
# it caches images in github docker repo
# then creates a manifest describing the final image
# and pushes it to dockerhub

jobs:
  build:
    strategy:
      matrix:
        os: [[self-hosted, linux, ARM64], ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate build info
        run: scripts/generate-git-info.sh > scripts/packages/git-info
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: 'ghcr.io/${{ github.repository }}:tmp-${{ github.sha }}-${{ runner.arch }}'
          cache-from: type=gha
          cache-to: type=gha,mode=max

  combine:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # I would love to avoid pulls here but not sure how to share data most effectively in this case
      # TODO: maybe use github actions cache API?
      - name: pull X64 image
        run: docker pull 'ghcr.io/${{ github.repository }}:tmp-${{ github.sha }}-X64'
      - name: pull ARM64 image
        run: docker pull 'ghcr.io/${{ github.repository }}:tmp-${{ github.sha }}-ARM64'
      # we have to create a manifest to make it work with different architectures
      - name: create manifest
        run: docker manifest create 'ghcr.io/${{ github.repository }}:git-${{ github.sha }}' 'ghcr.io/${{ github.repository }}:tmp-${{ github.sha }}-X64' 'ghcr.io/${{ github.repository }}:tmp-${{ github.sha }}-ARM64'
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.0'
      - name: install regctl
        run: git clone https://github.com/regclient/regclient.git && cd regclient && go build -o ../regctl ./cmd/regctl/
      - name: copy manifest to dockerhub
        run: ./regctl image copy 'ghcr.io/${{ github.repository }}:git-${{ github.sha }}' 'pyroscope/pyroscope-dev:git-${{ github.sha }}'
